name: "✨ Feature Request"
description: Feature request
title: "[Feature]: "
labels: ["feature request"]
assignees:
  - molunerfinn
body:
  - type: markdown
    attributes:
      value: |+
        ## PicGo Issue Template

        Please submit according to this template, otherwise it will be closed.
        **Before asking a question, please note that you have read the FAQ, Doc, and those closed issues. Otherwise the same question will also be closed!**

  - type: checkboxes
    id: read
    attributes:
      label: Pre-reading
      description: I have searched and read the following on my own (Please tick after reading)
      options:
        - label: "[Doc](https://picgo.github.io/PicGo-Doc/)"
          required: true
        - label: "[Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)"
          required: true
        - label: "[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)"
          required: true
  - type: input
    id: version
    attributes:
      label: PicGo Version
      placeholder: e.g. v2.3.0-beta.1
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: System Information
      options:
        - Windows
        - Mac
        - Mac(arm64)
        - Linux
        - All
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Feature request
      description: Describe in detail the features you envision or improvements to existing features
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Finally, if you like PicGo, give it a star~
        Buy me a cup of coffee if you can? There is a sponsorship QR code on the homepage, thank you for your support!